### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by fabio-marcelo** [ocbe-uio/rBAPS#14]
Hi. I've got the following error when trying to install.
> remotes::install_github("ocbe-uio/rBAPS", "dev")
Erro: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref dev

  Did you spell the repo owner (`ocbe-uio`) and repo name (`rBAPS`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

Can anybody help me, please?

**Comment by wleoncio** [comment]
Hi Fábio,

Thank you for your interest in rBAPS! I apologize for the typo in the README file. I'll fix it right away. The correct code for installation is

```r
remotes::install_github("ocbe-uio/rBAPS", "develop")
```

Please let me know when installation occurs successfully.

**Comment by wleoncio** [comment]
Hi @fabio-marcelo,

I was wondering if you're still running into problems installing rBAPS.

**Comment by fabio-marcelo** [comment]
Dear Waldir.
I hope this message finds you well.
It looks like the installation was ok but I haven't run rBAPS. I hope I can
do that in the future.
Thanks for your attention and support.
Have a great weekend.


Em sex., 3 de set. de 2021 às 02:50, Waldir Leoncio <
***@***.***> escreveu:

**Comment by wleoncio** [comment]
Thank you for your feedback. Since the installation itself is not a problem anymore this issue can be closed.

As for running rBAPS: there is still a lot of work to be done in the package so it works as one piece. Several functions have been translated from the original MATLAB code, but are yet to be connected so they can seamlessly work together.
